Website/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Backend.Data;
using Website.Models;
using Backend.Logic;


namespace Website.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookController _bookController;
        private readonly ICopyController _copyController;
        private readonly ILoanController _loanController;
        private string ifNullAuthor = "Stan Lee";

        public BookController(IBookController bookController, ICopyController copyController, ILoanController loanController)
        {
            _bookController = bookController;
            _copyController = copyController;
            _loanController = loanController;
        }

        public ActionResult Index(string searchTitle)
        {
            List<Backend.Data.Book> books = new List<Book>();
            //string searchTitle = Request["searchTitle"];
            books = string.IsNullOrEmpty(searchTitle) ? _bookController.GetBooksAmount(10) : _bookController.GetBooks(searchTitle);
            //List<Backend.Data.Book> books = _backendManager.BookController.GetBooks(searchTitle);
            List<VmBook> vmBooks = new List<VmBook>(books.Count);
            foreach (var book in books)
            {
                int copyCount = _copyController.CountCopies(book.Id);
                int copyCountNotLoaned = _loanController.CountCopysWithoutActiveLoan(book.Isbn10);
                string isbn = book.Isbn13 ?? book.Isbn10;
                string author = book?.Author?.FirstName + " " + book?.Author?.LastName;
                if (String.IsNullOrEmpty(author))
                    author = ifNullAuthor;
                var vmBook = new VmBook
                {
                    Isbn = isbn,
                    Title = book.Title,
                    CopyCount = copyCount,
                    CopyCountNotLoaned = copyCountNotLoaned,
                    Author = author
                };
                vmBooks.Add(vmBook);
            }
            return View(vmBooks);
        }

        // GET: Book
        //public ActionResult Index()
        //{
        //List<Backend.Data.Book> books = _backendManager.BookController.GetAllBooks();
        //List<VMBook> vmBooks = new List<VMBook>(books.Count);
        //foreach (var book in books)
        //{
        //    int copyCount = _backendManager.CopyController.GetCopies(book.Isbn10).Count;
        //    int copyCountNotLoaned = _backendManager.LoanController.GetCopysWithoutActiveLoan(book.Isbn10).Count;
        //    var vmBook = new VMBook
        //    {
        //        Isbn10 = book.Isbn10,
        //        Title = book.Title,
        //        CopyCount = copyCount,
        //        CopyCountNotLoaned = copyCountNotLoaned
        //    };
        //    vmBooks.Add(vmBook);
        //}
        //return View(/*vmBooks*/);
        //}

        //GET: Book/Details/*isbn*
        public ActionResult Details(string isbn)
        {
            VmBook vmBook = null;
            var book = _bookController.GetBook(isbn);
            if (book != null)
            {
                var copies = _copyController.GetCopies(book.Id);
                List<VmCopy> vmCopies = null;
                if (copies != null)
                {
                    vmCopies = new List<VmCopy>();
                    foreach (var copy in copies)
                    {
                        var loan = _loanController.GetLoanByCopyId(copy.Id);
                        VmCopy vmCopy = new VmCopy
                        {
                            Id = copy.Id,
                            IsLoaned = !loan?.LoanDone ?? false
                        };
                        vmCopies.Add(vmCopy);
                    }
                }
                vmBook = new VmBook
                {
                    Isbn = book.Isbn13 ?? book.Isbn10,
                    Title = book.Title,
                    Copies = vmCopies,
                    CopyCount = vmCopies != null ? vmCopies.Count : 0,
                    Author = String.IsNullOrWhiteSpace(book?.Author?.FirstName) ? ifNullAuthor : book?.Author?.FirstName
                };
            }
            return View(vmBook);
        }

        [HttpPost]
        public JsonResult GetBooksAjax(string searchTitle)
        {

            List<Backend.Data.Book> books = _bookController.GetBooks(searchTitle);
            List<VmBook> vmBooks = new List<VmBook>(books.Count);
            foreach (var book in books)
            {
                int copyCount = _copyController.GetCopies(book.Id).Count;
                int copyCountNotLoaned = _loanController.GetCopysWithoutActiveLoan(book.Isbn10).Count;
                var vmBook = new VmBook
                {
                    Isbn = book.Isbn10,
                    Title = book.Title,
                    CopyCount = copyCount,
                    CopyCountNotLoaned = copyCountNotLoaned
                };
                vmBooks.Add(vmBook);
            }

            //var json = new JavaScriptSerializer().Serialize(books);

            return Json(vmBooks);
        }
    }
}

Website/Controllers/LoanController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Backend.Logic;
using Website.Models;

namespace Website.Controllers
{
    public class LoanController : Controller
    {
        private readonly string MemberSSN = "98erihfd89d";

        private readonly IBookController _bookController;
        private readonly ICopyController _copyController;
        private readonly ILoanController _loanController;

        public LoanController(IBookController bookController, ICopyController copyController, ILoanController loanController)
        {
            _bookController = bookController;
            _copyController = copyController;
            _loanController = loanController;
        }

        // GET: Loan
        public ActionResult Index()
        {
            var loans = _loanController.GetLoans(MemberSSN);
            List<VmLoan> vmLoans = new List<VmLoan>();
            if (loans != null)
            {
                foreach (var loan in loans)
                {
                    var book = _bookController.GetBook(loan.LoanedCopy.Book.Id);
                    var vmBook = new VmBook
                    {
                        Title = book.Title
                    };
                    var vmLoan = new VmLoan
                    {
                        Id = loan.LoanNumber,
                        CreationDateTime = loan.CreationDateTime,
                        EndDateTime = loan.EndDateTime,
                        LoanDone = loan.LoanDone,
                        LoanedCopy = new VmCopy
                        {
                            Id = loan.LoanedCopy.Id,
                            VmBook = vmBook
                        }
                    };
                    vmLoans.Add(vmLoan);
                }
            }
            return View(vmLoans);
        }

        //// GET: Loan/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: Loan/Create
        public ActionResult Create(int copyId)
        {
            var vmLoan = CreateLoan(copyId);
            if (vmLoan != null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult End(int loanNumber)
        {
            var vmLoan = EndLoan(loanNumber);
            if (vmLoan == true)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        private bool EndLoan(int loanNumber)
        {
            return _loanController.EndLoan(loanNumber);
        }

        //// POST: Loan/Create
        //[HttpPost]
        //public ActionResult Create(int copyId)
        ////public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here
        //        var vmLoan = CreateLoan(copyId);
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        private VmLoan CreateLoan(int copyId)
        {
            var loan = _loanController.CreateLoan(copyId, MemberSSN);
            VmLoan vmLoan = null;
            if (loan != null)
            {
                var book = _bookController.GetBook(loan.LoanedCopy.Book.Id);
                var vmBook = new VmBook
                {
                    Isbn = book.Isbn13 ?? book.Isbn10
                };
                vmLoan = new VmLoan
                {
                    Id = loan.LoanNumber,
                    CreationDateTime = loan.CreationDateTime,
                    EndDateTime = loan.EndDateTime,
                    LoanedCopy = new VmCopy { Id = loan.LoanedCopy.Id, VmBook = vmBook, IsLoaned = true }
                };
            }
            return vmLoan;
        }

        //// GET: Loan/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Loan/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Loan/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Loan/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Website/Views/Book/Details.cshtml
@model Website.Models.VmBook

@{
    ViewBag.Title = "Book details";
    //Layout = "_Layout";
}

<h2>Book details</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Title)</th>
        <td>@Html.DisplayFor(model => model.Title)</td>
        <th>@Html.DisplayNameFor(model => model.Isbn)</th>
        <td>@Html.DisplayFor(model => model.Isbn)</td>
        <th>@Html.DisplayNameFor(model => model.Author)</th>
        <td>@Html.DisplayFor(model => model.Author)</td>
        <th>@Html.DisplayNameFor(model=> model.CopyCount)</th>
        <td>@Html.DisplayFor(model=> model.CopyCount)</td>
    </tr>
</table>

<h3>Available Copies</h3>
@if (Model?.Copies != null)
{
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Copies.First().Id)</th>
            @*<th>@Html.DisplayNameFor(model => model.Copies.First())</th>*@
            <th><p>Actions</p></th>
        </tr>
        @foreach (var item in Model.Copies)
        {
            if (!item.IsLoaned)
            {
                <tr>
                    <td>@Html.DisplayFor(model => item.Id)</td>
                    @*<td><p>Do stuff with this copy!</p></td>*@
                    <td><p>@Html.ActionLink("Loan it!", "Create", "Loan", new { copyId = item.Id }, null)</p></td>
                    @*<td><p>@Ajax.ActionLink("Loan it!", "Create", "Loan", new AjaxOptions { HttpMethod = "POST" })</p></td>*@
                </tr>
            }
        }
    </table>

}
else
{
    <p>None available</p>
}

Website/Views/Book/Index.cshtml
@model IEnumerable<Website.Models.VmBook>

@{
    ViewBag.Title = "View";
}
<div>
    <h2>Books</h2>

    <form method="get" action="@Url.Action("Index", "Book")">
        <label>Search</label>
        @Html.TextBox("searchTitle")
    </form>
</div>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<div id="tableWrap">
    <table id="table" class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Isbn)
                </th>
                <th>@Html.DisplayNameFor(model => model.Author)</th>
                <th>
                    @Html.DisplayNameFor(model => model.CopyCountPretty)
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Isbn)
                        </td>
                        <td>@Html.DisplayFor(modelitem => item.Author)</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CopyCountPretty)
                        </td>
                        <td>
                            @*@Html.ActionLink("Edit", "Edit", new { id=item.Isbn10 }) |*@
                            @Html.ActionLink("Details", "Details", new { isbn = item.Isbn })
                            @*@Html.ActionLink("Delete", "Details", new { id=item.Isbn10 })*@
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@*<script>
        var myData = "";

        $("#searchString").submit(function(event) {
            alert($("#searchValue").value());
            event.preventDefault();
        });

        $("#searchButton").click(function () {
            search($("#searchValue").val());
        });

        function search(searchString) {
            $.ajax({
                type: 'GET',
                contentType: "application/json; charset=utf-8",
                url: '/Book/Index',
                data: '{"searchTitle":' + searchString + ' }',
                async: false,
                success: function (response) {
                    myData = response;
                    $(function () {
                        $('#table').bootstrapTable({
                            data: myData
                        });
                    });
                },
                error: function () { alert("error"); }
            });
            return false;
        }
    </script>*@